[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "speech-integration"
authors = [
{ name = "Anil Keshwani", email = "anil.keshwani.academic@gmail.com" },
]
description = "Research implementation to investigate methods of integrating the speech modality into pre-trained language models"
requires-python = "==3.10.6"
license = { file = "LICENSE" }
dynamic = ["dependencies", "readme", "version"]

[tool.setuptools]
packages = ["ssi"] # Sardine Speech Integration

[tool.setuptools_scm]
version_file = "ssi/_version.py"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
readme = { file = ["README.md"] }

[project.optional-dependencies]
dev = [
"black==24.4.2",
"flake8",
"isort==5.13.2",
# "mypy",
"pipreqs==0.5.0",
"pre-commit==3.8.0",
"shfmt-py==3.7.0.1",
"usort==1.0.8",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
lines_after_imports = 2
force_alphabetical_sort_within_sections = true
