# Experiment management
experiments_root_dir: /mnt/scratch-artemis/anilkeshwani/experiments
output_dir: ${experiments_root_dir}/${base_model_name}

# Base models directory
extended_models_dir: /mnt/scratch-artemis/anilkeshwani/models/extended/
base_model_name: Llama-3.2-1B-5000-dsus

# DSUs
n_dsus: 5000

# Tokenizer - config for setup_llama3_tokenizer -> Llama3Tokenizer
tokenizer:
  path: ${extended_models_dir}/${base_model_name}/original/tokenizer.model
  max_seq_len: null # NOTE max seq. length 128_000_000 returned by `llama model describe -m Llama3.2-1B`
  prompt_template: null
  verbose: True

# Data
data:
  train:
    dataset:
      source: anilkeshwani/MLS_english_train_strat_sample_aligned_hubert_interleaved # specified as a HF dataset
      column: text
      split: train
      add_eos: True
    dataloader:
      shuffle: True
      batch_size: 4
    packed: False # TODO packing performed a priori at training time and leads to CPU RAM overflow for e.g. MLS interleaved
    # TODO clean up / describe the following fields (arguments)
    # split_across_pack: True # set to True for CPT; set to False for SFT
    # tokenizer: # set above
    # NOTE Following arguments copied across from text_completion_dataset docstring for reference
    # filter_fn: Optional[Callable] = None
    # **load_dataset_kwargs: Dict[str, Any]
  dev:
    dataset:
      source: anilkeshwani/MLS_english_train_strat_sample_aligned_hubert_interleaved # specified as a HF dataset
      column: text
      split: dev
      add_eos: True
    dataloader:
      shuffle: False
      batch_size: 4 # TODO can we increase this?
    packed: False

# Optimization
optimizer:
  lr: 2e-5
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.01
  amsgrad: False
  fused: True
max_steps: 10
gradient_accumulation_steps: 16
clip_grad_norm: null

# Learning rate scheduler
lr_scheduler:
  num_warmup_steps: 0
  num_cycles: 0.5

# Performance optimizations
optimizer_in_bwd: False # https://pytorch.org/tutorials/intermediate/optimizer_step_in_backward_tutorial.html
compile: False # set it to True for better memory and performance
# Memory management
enable_activation_checkpointing: False # True reduces memory
enable_activation_offloading: False # True reduces memory

# Training environment
device: cuda

# Reduced precision
dtype: bf16

# Checkpointing
checkpointer:
  checkpoint_dir: ???
  checkpoint_files: ???
  config_json: ???
  output_dir: null # if null -> resolved to ${output_dir}/${wandb_run_name}-id_{wandb_run_id}/checkpoints
  recipe_checkpoint: null
  adapter_checkpoint: null
  model_type: "llama3_2"
  safe_serialization: True

save_steps: 500 # checkpoint save period in **steps** (not iterations; i.e. with grad. accum.); should be multiple of eval_steps

# Evaluation
eval_steps: 250 # evaluation period **in steps** (not iterations; i.e. with grad. accum.)

# Logging
wandb:
  log_dir: ${output_dir}/wandb
  project: speech-integration
  entity: null # automatically set to username based on API key
  group: null
log_interval: 1
log_peak_memory_stats: False
