defaults: # inherit parameter values (Hydra inheritance syntax/functionality)
  - cpt
  - _self_

model_name: Llama-3.2-1B-5000-dsus # NOTE this percolates down to output_dir as resolution is lazy

data: # NOTE: arguments are to setup **function** not SFTDataset class
  train:
    # SFTDataset
    source: anilkeshwani/MLS_english_train_strat_sample_aligned_hubert
    # model_tokenizer taken from code
    inference: False # False for training, False for validation loss, toggled to True in code for validation inference
    filter_fn: null
    train_on_input: True # set to true to prevent forgetting; will hyperparam. search over this
    column_map:
      input: speech_tokens
      output: transcript
    new_system_prompt: "You will act as an automatic speech recognition (ASR) system. Transcribe the speech tokens into English text."
    image_dir: null

    # SFTDataset kwargs passed to datasets.load_dataset
    split: train

    # not arguments to SFT dataset:
    batch_size: 1 # passed to DataLoader
    drop_last: True # passed to DataLoader
    shuffle: True # passed to DistributedSampler
    packed: False # passed to pack_dataset to create a PackedDataset

    # arguments to remove from sft.yaml inherited from cpt.yaml # TODO find a cleaner way of dropping inherited keys
    column: null
    add_eos: null
  dev:
    # SFTDataset
    source: anilkeshwani/MLS_english_train_strat_sample_aligned_hubert
    # model_tokenizer taken from code
    inference: False # False for training, False for validation loss, toggled to True in code for validation inference
    filter_fn: null
    train_on_input: True # set to true to prevent forgetting; will hyperparam. search over this
    column_map:
      input: speech_tokens
      output: transcript
    new_system_prompt: "You will act as an automatic speech recognition (ASR) system. Transcribe the speech tokens into English text."
    image_dir: null

    # SFTDataset kwargs passed to datasets.load_dataset
    split: dev # <- NOTE different from train

    # not arguments to SFT dataset:
    batch_size: 1 # passed to DataLoader
    drop_last: False # passed to DataLoader
    shuffle: False # passed to DistributedSampler # <- NOTE different from train
    packed: False # passed to pack_dataset to create a PackedDataset

    # arguments to remove from sft.yaml inherited from cpt.yaml # TODO find a cleaner way of dropping inherited keys
    column: null
    add_eos: null
